### ISSUE TITLE
small read, write send garn parni rahex maily, capital READ, WRITE send garexu, error aayer ni save vayo

### ISSUE THREAD

**Issue by SahSantoshh** [SahSantoshh/nsa_api#30]

**Comment by sanzog03** [comment]
db seed ma ho bhane thik cha. last ma save hune capital mai ho. api call handa syano ma chayencha. farak pardaina

**Comment by SahSantoshh** [comment]
@sanzog03  I am aware about the seed part but this error is caused by API calls.
